---

- include: install.ppa.yml
  when: collectd_use_ppa
  tags: [collectd, collectd-install]

- include: install.deb.yml
  when: not collectd_use_ppa and ansible_os_family == 'Debian'
  tags: [collectd, collectd-install]

- include: configure.yml
  tags: [collectd, collectd-configure]

- include: configure-service.yml
  when: not collectd_use_ppa
  tags: [collectd, collectd-configure]
